### ISSUE TITLE
Outdated Virtual Box Guest Addition Version

### ISSUE THREAD

**Issue by lynscott** [udacity/fsnd-issues#30]

**Comment by lynscott** [comment]
![Screenshot (66).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5980e98952b88d001a22f5c5/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec0ba6dd6b0a65633b0ba92e7391a172fd1722545d0b4ffd415b5c46feab8b2ba6b43973de0e0fb8827f4366846c4ff8e7df46f554f832815d86b7b68b49c0e93b27e18b8e4e361e010ac4.png)

Got this error on `vagrant up` command from new VB version and old guest additions version. Found fix with:
sudo apt-get update
sudo apt-get install build-essential linux-headers-$(uname -r)
sudo apt-get install virtualbox-ose-guest-x11

<a href=https://askubuntu.com/questions/22743/how-do-i-install-guest-additions-in-a-virtualbox-vm>here</a>  from inside the VM. Unlesss you planted that bug on purpose for us to solve @_@

**Comment by SteveWooding** [comment]
No we didn't. Thanks for the solution though. Very resourceful of you. We've chosen to fix the version of the Vagrant box to a previous one that was working well. This update has only been made to the zip file download in the last day or so, so that's probably why you saw this issue. Going forward, this shouldn't be an issue for future students.
